In [3]:
import pandas as pd

In [5]:
#Windows user use \\ to the path
df = pd.read_csv('C:\\Users\\Jaydip dey\\Downloads\\Dataset_spine.csv')

In [6]:
df.shape

(310, 14)

In [7]:
df.head()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12,Class_att,Unnamed: 13
0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,0.744503,12.5661,14.5386,15.30468,-28.658501,43.5123,Abnormal,NaN
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,0.415186,12.8874,17.5323,16.78486,-25.530607,16.1102,Abnormal,NaN
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,0.474889,26.8343,17.4861,16.65897,-29.031888,19.2221,Abnormal,Prediction is done by using binary classificat...
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,0.369345,23.5603,12.7074,11.42447,-30.470246,18.8329,Abnormal,NaN
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,0.543360,35.4940,15.9546,8.87237,-16.378376,24.9171,Abnormal,NaN

In [8]:
df.columns

Index(['Col1', 'Col2', 'Col3', 'Col4', 'Col5', 'Col6', 'Col7', 'Col8', 'Col9',
       'Col10', 'Col11', 'Col12', 'Class_att', 'Unnamed: 13'],
      dtype='object')

In [9]:
df_col = {
    "Col1" : "pelvic_incidence", 
    "Col2" : "pelvic_tilt",
    "Col3" : "lumbar_lordosis_angle",
    "Col4" : "sacral_slope", 
    "Col5" : "pelvic_radius",
    "Col6" : "degree_spondylolisthesis", 
    "Col7" : "pelvic_slope",
    "Col8" : "direct_tilt",
    "Col9" : "thoracic_slope", 
    "Col10" :"cervical_tilt", 
    "Col11" : "sacrum_angle",
    "Col12" : "scoliosis_slope", 
    "Class_att" : "class",
    "Unnamed: 13": "remarks"
}

In [11]:
df_col

{'Col1': 'pelvic_incidence',
 'Col2': 'pelvic_tilt',
 'Col3': 'lumbar_lordosis_angle',
 'Col4': 'sacral_slope',
 'Col5': 'pelvic_radius',
 'Col6': 'degree_spondylolisthesis',
 'Col7': 'pelvic_slope',
 'Col8': 'direct_tilt',
 'Col9': 'thoracic_slope',
 'Col10': 'cervical_tilt',
 'Col11': 'sacrum_angle',
 'Col12': 'scoliosis_slope',
 'Class_att': 'class',
 'Unnamed: 13': 'remarks'}

In [15]:
df=df.rename(columns = df_col)

In [16]:
df.head()

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,remarks
0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,0.744503,12.5661,14.5386,15.30468,-28.658501,43.5123,Abnormal,NaN
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,0.415186,12.8874,17.5323,16.78486,-25.530607,16.1102,Abnormal,NaN
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,0.474889,26.8343,17.4861,16.65897,-29.031888,19.2221,Abnormal,Prediction is done by using binary classificat...
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,0.369345,23.5603,12.7074,11.42447,-30.470246,18.8329,Abnormal,NaN
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,0.543360,35.4940,15.9546,8.87237,-16.378376,24.9171,Abnormal,NaN

In [17]:
#NaN-->Not a Number

In [18]:
#identify how many NaN's are there in each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pelvic_incidence          310 non-null    float64
 1   pelvic_tilt               310 non-null    float64
 2   lumbar_lordosis_angle     310 non-null    float64
 3   sacral_slope              310 non-null    float64
 4   pelvic_radius             310 non-null    float64
 5   degree_spondylolisthesis  310 non-null    float64
 6   pelvic_slope              310 non-null    float64
 7   direct_tilt               310 non-null    float64
 8   thoracic_slope            310 non-null    float64
 9   cervical_tilt             310 non-null    float64
 10  sacrum_angle              310 non-null    float64
 11  scoliosis_slope           310 non-null    float64
 12  class                     310 non-null    object
 13  remarks                   14 non-null     object
dtypes: float64(12), object(2)
memory usage: 34.0+ KB

In [19]:
df2 = df.drop(columns = 'remarks')

In [21]:
df2.head()

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class
0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,0.744503,12.5661,14.5386,15.30468,-28.658501,43.5123,Abnormal
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,0.415186,12.8874,17.5323,16.78486,-25.530607,16.1102,Abnormal
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,0.474889,26.8343,17.4861,16.65897,-29.031888,19.2221,Abnormal
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,0.369345,23.5603,12.7074,11.42447,-30.470246,18.8329,Abnormal
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,0.543360,35.4940,15.9546,8.87237,-16.378376,24.9171,Abnormal

In [23]:
df2.describe()

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope
count,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000
mean,60.496653,17.542822,51.930930,42.953831,117.920655,26.296694,0.472979,21.321526,13.064511,11.933317,-14.053139,25.645981
std,17.236520,10.008330,18.554064,13.423102,13.317377,37.559027,0.285787,8.639423,3.399713,2.893265,12.225582,10.450558
min,26.147921,-6.554948,14.000000,13.366931,70.082575,-11.058179,0.003220,7.027000,7.037800,7.030600,-35.287375,7.007900
25%,46.430294,10.667069,37.000000,33.347122,110.709196,1.603727,0.224367,13.054400,10.417800,9.541140,-24.289522,17.189075
50%,58.691038,16.357689,49.562398,42.404912,118.268178,11.767934,0.475989,21.907150,12.938450,11.953835,-14.622856,24.931950
75%,72.877696,22.120395,63.000000,52.695888,125.467674,41.287352,0.704846,28.954075,15.889525,14.371810,-3.497094,33.979600
max,129.834041,49.431864,125.742385,121.429566,163.071041,418.543082,0.998827,36.743900,19.324000,16.821080,6.972071,44.341200

In [24]:
df2.describe( include="all")

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class
count,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000,310
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abnormal
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210
mean,60.496653,17.542822,51.930930,42.953831,117.920655,26.296694,0.472979,21.321526,13.064511,11.933317,-14.053139,25.645981,NaN
std,17.236520,10.008330,18.554064,13.423102,13.317377,37.559027,0.285787,8.639423,3.399713,2.893265,12.225582,10.450558,NaN
min,26.147921,-6.554948,14.000000,13.366931,70.082575,-11.058179,0.003220,7.027000,7.037800,7.030600,-35.287375,7.007900,NaN
25%,46.430294,10.667069,37.000000,33.347122,110.709196,1.603727,0.224367,13.054400,10.417800,9.541140,-24.289522,17.189075,NaN
50%,58.691038,16.357689,49.562398,42.404912,118.268178,11.767934,0.475989,21.907150,12.938450,11.953835,-14.622856,24.931950,NaN
75%,72.877696,22.120395,63.000000,52.695888,125.467674,41.287352,0.704846,28.954075,15.889525,14.371810,-3.497094,33.979600,NaN
max,129.834041,49.431864,125.742385,121.429566,163.071041,418.543082,0.998827,36.743900,19.324000,16.821080,6.972071,44.341200,NaN

In [26]:
df2["class"].value_counts()

Abnormal    210
Normal      100
Name: class, dtype: int64

In [29]:
df2["record_id"] = range(1,len(df2)+1)

In [30]:
df2.head()

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,0.744503,12.5661,14.5386,15.30468,-28.658501,43.5123,Abnormal,1
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,0.415186,12.8874,17.5323,16.78486,-25.530607,16.1102,Abnormal,2
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,0.474889,26.8343,17.4861,16.65897,-29.031888,19.2221,Abnormal,3
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,0.369345,23.5603,12.7074,11.42447,-30.470246,18.8329,Abnormal,4
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,0.543360,35.4940,15.9546,8.87237,-16.378376,24.9171,Abnormal,5

In [32]:
list(range(1,5))

[1, 2, 3, 4]

In [33]:
len(df2)

310

In [40]:
import numpy as np

In [42]:
df2.iloc[0:5,-1] = np.NaN

In [43]:
df2.head(10)

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,0.744503,12.5661,14.5386,15.30468,-28.658501,43.5123,Abnormal,NaN
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,0.415186,12.8874,17.5323,16.78486,-25.530607,16.1102,Abnormal,NaN
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,0.474889,26.8343,17.4861,16.65897,-29.031888,19.2221,Abnormal,NaN
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,0.369345,23.5603,12.7074,11.42447,-30.470246,18.8329,Abnormal,NaN
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,0.543360,35.4940,15.9546,8.87237,-16.378376,24.9171,Abnormal,NaN
5,40.250200,13.921907,25.124950,26.328293,130.327871,2.230652,0.789993,29.3230,12.0036,10.40462,-1.512209,9.6548,Abnormal,6.0
6,53.432928,15.864336,37.165934,37.568592,120.567523,5.988551,0.198920,13.8514,10.7146,11.37832,-20.510434,25.9477,Abnormal,7.0
7,45.366754,10.755611,29.038349,34.611142,117.270068,-10.675871,0.131973,28.8165,7.7676,7.60961,-25.111459,26.3543,Abnormal,8.0
8,43.790190,13.533753,42.690814,30.256437,125.002893,13.289018,0.190408,22.7085,11.4234,10.59188,-20.020075,40.0276,Abnormal,9.0
9,36.686353,5.010884,41.948751,31.675469,84.241415,0.664437,0.367700,26.2011,8.7380,14.91416,-1.702097,21.4320,Abnormal,10.0

In [45]:
#Check how many NaN values are there
df2.record_id.isna()

0       True
1       True
2       True
3       True
4       True
       ...
305    False
306    False
307    False
308    False
309    False
Name: record_id, Length: 310, dtype: bool

In [50]:
df2.record_id.isna().value_counts()

False    305
True       5
Name: record_id, dtype: int64

In [47]:
df2.record_id.isna().sum()

5

In [52]:
df2 = df2.dropna()

In [53]:
df2.head()

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
5,40.250200,13.921907,25.124950,26.328293,130.327871,2.230652,0.789993,29.3230,12.0036,10.40462,-1.512209,9.6548,Abnormal,6.0
6,53.432928,15.864336,37.165934,37.568592,120.567523,5.988551,0.198920,13.8514,10.7146,11.37832,-20.510434,25.9477,Abnormal,7.0
7,45.366754,10.755611,29.038349,34.611142,117.270068,-10.675871,0.131973,28.8165,7.7676,7.60961,-25.111459,26.3543,Abnormal,8.0
8,43.790190,13.533753,42.690814,30.256437,125.002893,13.289018,0.190408,22.7085,11.4234,10.59188,-20.020075,40.0276,Abnormal,9.0
9,36.686353,5.010884,41.948751,31.675469,84.241415,0.664437,0.367700,26.2011,8.7380,14.91416,-1.702097,21.4320,Abnormal,10.0

In [54]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 305 entries, 5 to 309
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pelvic_incidence          305 non-null    float64
 1   pelvic_tilt               305 non-null    float64
 2   lumbar_lordosis_angle     305 non-null    float64
 3   sacral_slope              305 non-null    float64
 4   pelvic_radius             305 non-null    float64
 5   degree_spondylolisthesis  305 non-null    float64
 6   pelvic_slope              305 non-null    float64
 7   direct_tilt               305 non-null    float64
 8   thoracic_slope            305 non-null    float64
 9   cervical_tilt             305 non-null    float64
 10  sacrum_angle              305 non-null    float64
 11  scoliosis_slope           305 non-null    float64
 12  class                     305 non-null    object
 13  record_id                 305 non-null    float64
dtypes: float64(13), object(1)
memory usage: 35.7+ KB

In [56]:
df2.isna().sum()

pelvic_incidence            0
pelvic_tilt                 0
lumbar_lordosis_angle       0
sacral_slope                0
pelvic_radius               0
degree_spondylolisthesis    0
pelvic_slope                0
direct_tilt                 0
thoracic_slope              0
cervical_tilt               0
sacrum_angle                0
scoliosis_slope             0
class                       0
record_id                   0
dtype: int64

In [59]:
#How to save this df
df2.to_csv('new_spine_data.csv')

In [62]:
# How to convert datatype of a column
df2.record_id = df2.record_id.astype(int)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [63]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 305 entries, 5 to 309
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pelvic_incidence          305 non-null    float64
 1   pelvic_tilt               305 non-null    float64
 2   lumbar_lordosis_angle     305 non-null    float64
 3   sacral_slope              305 non-null    float64
 4   pelvic_radius             305 non-null    float64
 5   degree_spondylolisthesis  305 non-null    float64
 6   pelvic_slope              305 non-null    float64
 7   direct_tilt               305 non-null    float64
 8   thoracic_slope            305 non-null    float64
 9   cervical_tilt             305 non-null    float64
 10  sacrum_angle              305 non-null    float64
 11  scoliosis_slope           305 non-null    float64
 12  class                     305 non-null    object
 13  record_id                 305 non-null    int32
dtypes: float64(12), int32(1), object(1)
memory usage: 34.6+ KB

In [64]:
df2.to_csv("C:\\Users\\Jaydip dey\\Desktop\\anything.csv")

In [65]:
# loc : identifying the location/filtering of data

In [67]:
df2.head()

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
5,40.250200,13.921907,25.124950,26.328293,130.327871,2.230652,0.789993,29.3230,12.0036,10.40462,-1.512209,9.6548,Abnormal,6
6,53.432928,15.864336,37.165934,37.568592,120.567523,5.988551,0.198920,13.8514,10.7146,11.37832,-20.510434,25.9477,Abnormal,7
7,45.366754,10.755611,29.038349,34.611142,117.270068,-10.675871,0.131973,28.8165,7.7676,7.60961,-25.111459,26.3543,Abnormal,8
8,43.790190,13.533753,42.690814,30.256437,125.002893,13.289018,0.190408,22.7085,11.4234,10.59188,-20.020075,40.0276,Abnormal,9
9,36.686353,5.010884,41.948751,31.675469,84.241415,0.664437,0.367700,26.2011,8.7380,14.91416,-1.702097,21.4320,Abnormal,10

In [69]:
### LOC SYNTAX ###
# df.loc[  condition for rows/row name ,   condition for columns /column name ]

In [70]:
df2.loc[df2.pelvic_incidence>65.0]

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
29,66.879211,24.891999,49.278597,41.987212,113.477018,-2.005892,0.677268,12.4271,8.2495,7.58784,-3.963385,27.3587,Abnormal,30
43,66.285394,26.327845,47.500000,39.957549,121.219684,-0.799624,0.647626,9.0466,10.2636,13.50349,1.138079,34.3683,Abnormal,44
51,74.433593,41.557331,27.700000,32.876262,107.949304,5.000089,0.606768,32.6283,9.8062,11.62142,-10.028289,9.3141,Abnormal,52
60,74.377678,32.053104,78.772013,42.324573,143.560690,56.125906,0.159378,35.9529,15.3975,11.71169,-18.628293,22.5623,Abnormal,61
61,89.680567,32.704435,83.130732,56.976132,129.955476,92.027277,0.527584,26.3756,18.6012,16.09596,-18.701330,35.8729,Abnormal,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,67.804694,16.550662,43.256802,51.254033,119.685645,4.867540,0.036158,18.4894,15.4016,13.86568,-17.473008,39.3526,Normal,286
288,74.565015,15.724320,58.618582,58.840695,105.417304,0.599247,0.117780,18.0547,15.6236,10.54562,-32.494544,16.6229,Normal,289
298,66.507179,20.897672,31.727471,45.609507,128.902905,1.517203,0.787252,12.8877,11.8978,9.23220,-14.824364,43.8409,Normal,299
299,82.905351,29.894119,58.250542,53.011232,110.708958,6.079338,0.827146,12.5622,12.3646,16.61754,-15.758791,35.9458,Normal,300
301,89.014875,26.075981,69.021259,62.938894,111.481075,6.061508,0.544505,27.0219,13.3731,11.04819,-3.505300,33.4196,Normal,302

In [71]:
df2.loc[df2.pelvic_incidence>65.0 , "record_id"]

29      30
43      44
51      52
60      61
61      62
      ...
285    286
288    289
298    299
299    300
301    302
Name: record_id, Length: 119, dtype: int32

In [73]:
df2.loc[df2.pelvic_incidence>65.0 , ["record_id" , "pelvic_incidence"]]

     record_id  pelvic_incidence
29          30         66.879211
43          44         66.285394
51          52         74.433593
60          61         74.377678
61          62         89.680567
..         ...               ...
285        286         67.804694
288        289         74.565015
298        299         66.507179
299        300         82.905351
301        302         89.014875

[119 rows x 2 columns]

In [83]:
df2.loc[(df2["class"]=="Normal") & (df2.pelvic_incidence > 65.0)]

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
223,69.398818,18.898407,75.966361,50.500411,103.582540,-0.443661,0.647609,29.0187,13.1408,9.58711,-22.403652,12.5917,Normal,224
224,89.834676,22.639217,90.563461,67.195460,100.501192,3.040973,0.379933,9.4868,17.7556,10.98189,-16.891891,28.0900,Normal,225
230,65.611802,23.137919,62.582179,42.473883,124.128001,-4.083298,0.997247,30.0422,17.6222,13.39076,-16.369970,21.4495,Normal,231
238,69.004913,13.291790,55.570143,55.713123,126.611622,10.832011,0.385073,35.4534,7.4752,7.76405,-11.716465,13.0886,Normal,239
254,72.955644,19.576971,61.007071,53.378673,111.234047,0.813491,0.409586,25.4781,12.4063,7.05411,-9.046640,16.8122,Normal,255
255,67.538182,14.655042,58.001429,52.883139,123.632260,25.970206,0.330439,8.3510,9.9145,16.25839,-27.302888,25.0493,Normal,256
261,74.976021,14.921705,53.730072,60.054317,105.645400,1.594748,0.318967,13.2564,11.3042,13.47166,-20.789258,41.2149,Normal,262
275,67.289712,16.717514,51.000000,50.572198,137.591778,4.960344,0.233195,23.3207,13.7148,10.46265,-9.187554,27.8587,Normal,276
277,65.756348,13.206926,44.000000,52.549422,129.393573,-1.982120,0.727537,33.2640,17.5228,8.31382,6.972071,31.7892,Normal,278
285,67.804694,16.550662,43.256802,51.254033,119.685645,4.867540,0.036158,18.4894,15.4016,13.86568,-17.473008,39.3526,Normal,286
288,74.565015,15.724320,58.618582,58.840695,105.417304,0.599247,0.117780,18.0547,15.6236,10.54562,-32.494544,16.6229,Normal,289
298,66.507179,20.897672,31.727471,45.609507,128.902905,1.517203,0.787252,12.8877,11.8978,9.23220,-14.824364,43.8409,Normal,299
299,82.905351,29.894119,58.250542,53.011232,110.708958,6.079338,0.827146,12.5622,12.3646,16.61754,-15.758791,35.9458,Normal,300
301,89.014875,26.075981,69.021259,62.938894,111.481075,6.061508,0.544505,27.0219,13.3731,11.04819,-3.505300,33.4196,Normal,302

In [84]:
### SYNTAX FOR MULTIPLE CONDITION IN LOC ###
# df.loc[(condition1) & (condition2) & (condition3)]

In [85]:
# When you want all conditions to be true please use &       (AND)
# When you want any one condition to be true please use |    (OR)

In [86]:
df2.loc[(df2["class"]=="Normal") | (df2.pelvic_incidence > 65.0)]

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
29,66.879211,24.891999,49.278597,41.987212,113.477018,-2.005892,0.677268,12.4271,8.2495,7.58784,-3.963385,27.3587,Abnormal,30
43,66.285394,26.327845,47.500000,39.957549,121.219684,-0.799624,0.647626,9.0466,10.2636,13.50349,1.138079,34.3683,Abnormal,44
51,74.433593,41.557331,27.700000,32.876262,107.949304,5.000089,0.606768,32.6283,9.8062,11.62142,-10.028289,9.3141,Abnormal,52
60,74.377678,32.053104,78.772013,42.324573,143.560690,56.125906,0.159378,35.9529,15.3975,11.71169,-18.628293,22.5623,Abnormal,61
61,89.680567,32.704435,83.130732,56.976132,129.955476,92.027277,0.527584,26.3756,18.6012,16.09596,-18.701330,35.8729,Abnormal,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,47.903565,13.616688,36.000000,34.286877,117.449062,-4.245395,0.129744,7.8433,14.7484,8.51707,-15.728927,11.5472,Normal,306
306,53.936748,20.721496,29.220534,33.215251,114.365845,-0.421010,0.047913,19.1986,18.1972,7.08745,6.013843,43.8693,Normal,307
307,61.446597,22.694968,46.170347,38.751628,125.670725,-2.707880,0.081070,16.2059,13.5565,8.89572,3.564463,18.4151,Normal,308
308,45.252792,8.693157,41.583126,36.559635,118.545842,0.214750,0.159251,14.7334,16.0928,9.75922,5.767308,33.7192,Normal,309
309,33.841641,5.073991,36.641233,28.767649,123.945244,-0.199249,0.674504,19.3825,17.6963,13.72929,1.783007,40.6049,Normal,310

In [91]:
df2.loc[(df2.sacral_slope > 25) & (df2.sacral_slope < 35)]

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
5,40.250200,13.921907,25.124950,26.328293,130.327871,2.230652,0.789993,29.3230,12.0036,10.40462,-1.512209,9.6548,Abnormal,6
7,45.366754,10.755611,29.038349,34.611142,117.270068,-10.675871,0.131973,28.8165,7.7676,7.60961,-25.111459,26.3543,Abnormal,8
8,43.790190,13.533753,42.690814,30.256437,125.002893,13.289018,0.190408,22.7085,11.4234,10.59188,-20.020075,40.0276,Abnormal,9
9,36.686353,5.010884,41.948751,31.675469,84.241415,0.664437,0.367700,26.2011,8.7380,14.91416,-1.702097,21.4320,Abnormal,10
12,48.915551,19.964556,40.263794,28.950995,119.321358,8.028895,0.139478,32.7916,7.2049,8.61882,-1.215542,27.3713,Abnormal,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,34.382299,2.062683,32.390820,32.319617,128.300199,-3.365516,0.581169,12.0774,16.6255,7.20496,-31.374823,29.5748,Normal,304
304,45.075450,12.306951,44.583177,32.768499,147.894637,-8.941709,0.932922,32.1169,14.3037,10.64326,-31.198847,11.2307,Normal,305
305,47.903565,13.616688,36.000000,34.286877,117.449062,-4.245395,0.129744,7.8433,14.7484,8.51707,-15.728927,11.5472,Normal,306
306,53.936748,20.721496,29.220534,33.215251,114.365845,-0.421010,0.047913,19.1986,18.1972,7.08745,6.013843,43.8693,Normal,307
309,33.841641,5.073991,36.641233,28.767649,123.945244,-0.199249,0.674504,19.3825,17.6963,13.72929,1.783007,40.6049,Normal,310

In [92]:
#loc  - name based searhcing 
#iloc - number based searching

In [100]:
df2.loc[df2.pelvic_incidence > 100]

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
115,129.834041,8.404475,48.384057,121.429566,107.690466,418.543082,0.860223,18.5943,11.1514,11.36543,-34.202073,27.5144,Abnormal,116
162,118.144655,38.449501,50.838520,79.695154,81.024541,74.043767,0.599393,35.8563,10.9266,13.11354,-17.520810,21.2408,Abnormal,163
163,115.923261,37.515436,76.800000,78.407825,104.698603,81.198927,0.542816,22.3317,8.8519,11.48960,-6.754004,32.5082,Abnormal,164

In [101]:
df2.loc[df2.pelvic_incidence > 100, "pelvic_incidence"]

115    129.834041
162    118.144655
163    115.923261
Name: pelvic_incidence, dtype: float64

In [102]:
df2.loc[df2.pelvic_incidence > 100, "pelvic_incidence"] = 100

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [103]:
df2.loc[df.pelvic_incidence > 99]

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
115,100.0,8.404475,48.384057,121.429566,107.690466,418.543082,0.860223,18.5943,11.1514,11.36543,-34.202073,27.5144,Abnormal,116
162,100.0,38.449501,50.838520,79.695154,81.024541,74.043767,0.599393,35.8563,10.9266,13.11354,-17.520810,21.2408,Abnormal,163
163,100.0,37.515436,76.800000,78.407825,104.698603,81.198927,0.542816,22.3317,8.8519,11.48960,-6.754004,32.5082,Abnormal,164

In [104]:
df2.head()

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
5,40.250200,13.921907,25.124950,26.328293,130.327871,2.230652,0.789993,29.3230,12.0036,10.40462,-1.512209,9.6548,Abnormal,6
6,53.432928,15.864336,37.165934,37.568592,120.567523,5.988551,0.198920,13.8514,10.7146,11.37832,-20.510434,25.9477,Abnormal,7
7,45.366754,10.755611,29.038349,34.611142,117.270068,-10.675871,0.131973,28.8165,7.7676,7.60961,-25.111459,26.3543,Abnormal,8
8,43.790190,13.533753,42.690814,30.256437,125.002893,13.289018,0.190408,22.7085,11.4234,10.59188,-20.020075,40.0276,Abnormal,9
9,36.686353,5.010884,41.948751,31.675469,84.241415,0.664437,0.367700,26.2011,8.7380,14.91416,-1.702097,21.4320,Abnormal,10

In [106]:
df2.loc[4]

KeyError: 4

In [108]:
df2.head()

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
5,40.250200,13.921907,25.124950,26.328293,130.327871,2.230652,0.789993,29.3230,12.0036,10.40462,-1.512209,9.6548,Abnormal,6
6,53.432928,15.864336,37.165934,37.568592,120.567523,5.988551,0.198920,13.8514,10.7146,11.37832,-20.510434,25.9477,Abnormal,7
7,45.366754,10.755611,29.038349,34.611142,117.270068,-10.675871,0.131973,28.8165,7.7676,7.60961,-25.111459,26.3543,Abnormal,8
8,43.790190,13.533753,42.690814,30.256437,125.002893,13.289018,0.190408,22.7085,11.4234,10.59188,-20.020075,40.0276,Abnormal,9
9,36.686353,5.010884,41.948751,31.675469,84.241415,0.664437,0.367700,26.2011,8.7380,14.91416,-1.702097,21.4320,Abnormal,10

In [111]:
df2.iloc[:5]

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,pelvic_slope,direct_tilt,thoracic_slope,cervical_tilt,sacrum_angle,scoliosis_slope,class,record_id
5,40.250200,13.921907,25.124950,26.328293,130.327871,2.230652,0.789993,29.3230,12.0036,10.40462,-1.512209,9.6548,Abnormal,6
6,53.432928,15.864336,37.165934,37.568592,120.567523,5.988551,0.198920,13.8514,10.7146,11.37832,-20.510434,25.9477,Abnormal,7
7,45.366754,10.755611,29.038349,34.611142,117.270068,-10.675871,0.131973,28.8165,7.7676,7.60961,-25.111459,26.3543,Abnormal,8
8,43.790190,13.533753,42.690814,30.256437,125.002893,13.289018,0.190408,22.7085,11.4234,10.59188,-20.020075,40.0276,Abnormal,9
9,36.686353,5.010884,41.948751,31.675469,84.241415,0.664437,0.367700,26.2011,8.7380,14.91416,-1.702097,21.4320,Abnormal,10

In [114]:
df2.iloc[:5, 1]

5    13.921907
6    15.864336
7    10.755611
8    13.533753
9     5.010884
Name: pelvic_tilt, dtype: float64

In [116]:
df2.iloc[:5, [0,1,3, -1]]

   pelvic_incidence  pelvic_tilt  sacral_slope  record_id
5         40.250200    13.921907     26.328293          6
6         53.432928    15.864336     37.568592          7
7         45.366754    10.755611     34.611142          8
8         43.790190    13.533753     30.256437          9
9         36.686353     5.010884     31.675469         10